name: Hello workflow

on:
  push:
    branches:
      - main
permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
      
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello world
        run: echo "Hello World"
        shell: bash
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AMI_ROLE }} #arn:aws:iam::870997468983:role/sandipanOIDC
          role-session-name: samplerolesession
          aws-region: ap-south-1
      - name: check s3 list
        run: |
          aws s3 ls
  goodbye:
     runs-on: ubuntu-latest
     steps:
       - name: Goodbye
         run : echo "GoodBye World"
         shell: bash
